// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodicTable;

namespace PeriodicTable.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190721164700_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeriodicTable.Models.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AtomicNumber");

                    b.Property<double>("AtomicWeight");

                    b.Property<string>("Class");

                    b.Property<string>("Description");

                    b.Property<int?>("GroupId");

                    b.Property<int>("GroupdId");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("PeriodId");

                    b.Property<string>("Symbol");

                    b.HasKey("ElementId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Elements");

                    b.HasData(
                        new { ElementId = 1, AtomicNumber = 1, AtomicWeight = 1.07794, Class = "NonMetal", Description = "HydrogenHydrogen", GroupdId = 1, Image = "https://metaphysicalexperience.files.wordpress.com/2010/06/physical-universe.jpg", Name = "Hydrogen", PeriodId = 1, Symbol = "H" }
                    );
                });

            modelBuilder.Entity("PeriodicTable.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new { GroupId = 1 }
                    );
                });

            modelBuilder.Entity("PeriodicTable.Models.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");

                    b.HasData(
                        new { PeriodId = 1 }
                    );
                });

            modelBuilder.Entity("PeriodicTable.Models.Element", b =>
                {
                    b.HasOne("PeriodicTable.Models.Group")
                        .WithMany("Elements")
                        .HasForeignKey("GroupId");

                    b.HasOne("PeriodicTable.Models.Period")
                        .WithMany("Elements")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
