// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeriodicTable;

namespace PeriodicTable.Migrations
{
    [DbContext(typeof(SiteContext))]
    [Migration("20190723002322_testm6")]
    partial class testm6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PeriodicTable.Models.Element", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AtomicNumber");

                    b.Property<double>("AtomicWeight");

                    b.Property<string>("Class");

                    b.Property<string>("Description");

                    b.Property<int>("GroupId");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("PeriodId");

                    b.Property<string>("Symbol");

                    b.HasKey("ElementId");

                    b.HasIndex("GroupId");

                    b.HasIndex("PeriodId");

                    b.ToTable("Elements");

                    b.HasData(
                        new { ElementId = 1, AtomicNumber = 1, AtomicWeight = 1.07794, Class = "PN", Description = "HydrogenHydrogen", GroupId = 1, Image = "https://metaphysicalexperience.files.wordpress.com/2010/06/physical-universe.jpg", Name = "Hydrogen", PeriodId = 1, Symbol = "H" },
                        new { ElementId = 2, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 2, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 3, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 3, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 4, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 4, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 5, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 5, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 6, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 6, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 7, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 7, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 8, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 8, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 9, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 9, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 10, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 10, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 11, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 11, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 12, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 12, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 13, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 13, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 14, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 14, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 15, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 15, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 16, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 16, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 17, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 17, Image = "", Name = "ADD NEW", PeriodId = 1, Symbol = "+" },
                        new { ElementId = 18, AtomicNumber = 2, AtomicWeight = 4.003, Class = "NG", Description = "", GroupId = 18, Image = "", Name = "Helium", PeriodId = 1, Symbol = "HE" },
                        new { ElementId = 19, AtomicNumber = 3, AtomicWeight = 6.941, Class = "AM", Description = "", GroupId = 1, Image = "", Name = "Lithium", PeriodId = 2, Symbol = "LI" },
                        new { ElementId = 20, AtomicNumber = 4, AtomicWeight = 9.012, Class = "AEM", Description = "", GroupId = 2, Image = "", Name = "Beryllium", PeriodId = 2, Symbol = "BE" },
                        new { ElementId = 21, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 3, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 22, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 4, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 23, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 5, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 24, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 6, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 25, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 7, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 26, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 8, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 27, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 9, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 28, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 10, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 29, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 11, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 30, AtomicNumber = 1, AtomicWeight = 0.0, Class = "NON", Description = "", GroupId = 12, Image = "", Name = "ADD NEW", PeriodId = 2, Symbol = "+" },
                        new { ElementId = 31, AtomicNumber = 5, AtomicWeight = 10.811, Class = "M", Description = "", GroupId = 13, Image = "", Name = "Boron", PeriodId = 2, Symbol = "B" },
                        new { ElementId = 32, AtomicNumber = 6, AtomicWeight = 12.011, Class = "PN", Description = "", GroupId = 14, Image = "", Name = "Carbon", PeriodId = 2, Symbol = "C" },
                        new { ElementId = 33, AtomicNumber = 7, AtomicWeight = 14.007, Class = "PN", Description = "", GroupId = 15, Image = "", Name = "Nitrogen", PeriodId = 2, Symbol = "N" },
                        new { ElementId = 34, AtomicNumber = 8, AtomicWeight = 15.999, Class = "PN", Description = "", GroupId = 16, Image = "", Name = "Oxygen", PeriodId = 2, Symbol = "O" },
                        new { ElementId = 35, AtomicNumber = 9, AtomicWeight = 18.998, Class = "DN", Description = "", GroupId = 17, Image = "", Name = "Flourine", PeriodId = 2, Symbol = "F" },
                        new { ElementId = 36, AtomicNumber = 10, AtomicWeight = 20.18, Class = "NG", Description = "", GroupId = 18, Image = "", Name = "Neon", PeriodId = 2, Symbol = "Ne" }
                    );
                });

            modelBuilder.Entity("PeriodicTable.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new { GroupId = 1 },
                        new { GroupId = 2 },
                        new { GroupId = 3 },
                        new { GroupId = 4 },
                        new { GroupId = 5 },
                        new { GroupId = 6 },
                        new { GroupId = 7 },
                        new { GroupId = 8 },
                        new { GroupId = 9 },
                        new { GroupId = 10 },
                        new { GroupId = 11 },
                        new { GroupId = 12 },
                        new { GroupId = 13 },
                        new { GroupId = 14 },
                        new { GroupId = 15 },
                        new { GroupId = 16 },
                        new { GroupId = 17 },
                        new { GroupId = 18 }
                    );
                });

            modelBuilder.Entity("PeriodicTable.Models.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("PeriodId");

                    b.ToTable("Periods");

                    b.HasData(
                        new { PeriodId = 1 },
                        new { PeriodId = 2 },
                        new { PeriodId = 3 },
                        new { PeriodId = 4 },
                        new { PeriodId = 5 },
                        new { PeriodId = 6 },
                        new { PeriodId = 7 }
                    );
                });

            modelBuilder.Entity("PeriodicTable.Models.Element", b =>
                {
                    b.HasOne("PeriodicTable.Models.Group")
                        .WithMany("Elements")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PeriodicTable.Models.Period")
                        .WithMany("Elements")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
